### ISSUE TITLE
Improvements to CSV files on Google Drive

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#381]
## Intro

On the CSV to Docs page, we have steps on "[Using CSV files on Google Drive](https://docs.communityhealthtoolkit.org/apps/guides/data/csv-to-docs/#using-csv-files-on-google-drive)" steps.  I think they could use some minor improvements.

## Improvements

1. In the "Using CSV files on Google Drive", the first section, you're instructed to run `medic-conf fetch-csvs-from-google-drive`.  However, this won't work until you create a `.gdrive.secrets.json` file and correctly populate that file.  The step to create `.gdrive.secrets.json` is two sections below the instruction to run `fetch-csvs-from-google-drive`, so it's initially confusing.  We should consider re-ordering these steps
1. In the "Linking to Google Drive" section we have the following JSON because it has a trailing comma ("`,`").  We should either add a second line w/o a trailing comma or remove the one a single line:
   ```json
   {
       "person.clinic.csv":"google_drive_ID",
   }
   ```
1. There's woah-so-many options when creating your Oath2 token.  We should give a few more hints about what to do (eg. create a  token for google spreadsheet, not google drive, be sure to give an apt name like "medic-conf" etc)
1. `token_uri` value in the `.gdrive.secrets.json` file has changed. We should either remove it and force the user to enter it, or update it to `https://oauth2.googleapis.com/token`
1. we may consider adding some common error messages when setting this up (see below).
1. It might be helpful to let tu user know they'll be redirected google's site to login and the will need to copy and paste the value back to the `medic-conf` terminal which is prompting them. `Enter access code from browser: `. We could also possibly include a screenshot.

## Common errors

If you have an extra comma in your 

```
WARN Error parsing JSON in: /home/mrjones/Documents/MedicMobile/cht-core/config/default/csvs-on-google-drive.json 
ERROR SyntaxError: Unexpected token } in JSON at position 80
    at JSON.parse (<anonymous>)
    at Object.readJson (/usr/lib/node_modules/medic-conf/src/lib/sync-fs.js:29:17)
    at /usr/lib/node_modules/medic-conf/src/lib/fetch-files-from-google-drive.js:12:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (/usr/lib/node_modules/medic-conf/src/fn/fetch-csvs-from-google-drive.js:7:5)
    at async module.exports (/usr/lib/node_modules/medic-conf/src/lib/main.js:185:5)
    at async /usr/lib/node_modules/medic-conf/src/bin/medic-conf.js:11:18 
```

I got this error and actually don't know how to resolve it ;)  But when I do figure it out, I'll update this ticket!

```
INFO Exporting 1t[SNIP]2w from google drive to /home/mrjones/Documents/MedicMobile/cht-core/config/default/csv/DRAFT_child_monitoring.csv… 
ERROR Error: [object Object]
    at Gaxios._request (/usr/lib/node_modules/medic-conf/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OAuth2Client.requestAsync (/usr/lib/node_modules/medic-conf/node_modules/google-auth-library/build/src/auth/oauth2client.js:350:18) 
```

**Comment by mrjones-plip** [comment]
@abbyad - thanks for your help on the call earlier today! I got with @newtewt and we figured that the bad session from my failed Oauth app setup was being cached in `.gdrive.session.json`. Once I removed that and recreated it with our secrets file in 1pass, everything worked.  

I'm gonna punt on this ticket for now 'til a later date, but happy to dive into when we want prioritize it.  The biggie I think is that per `#3` above, we don't dive into enough detail on to set this up correctly on the google side.

FYI @michaelkohn
